### ISSUE TITLE
no MFR  memory in guide

### ISSUE THREAD

**Issue by shikulja** [integralfx/MemTestHelper#12]
there is no MFR and some others in the guide.
Unfortunately, for happy circumstances, I became the owner of such a wonderful memory.

found information for myself here.
https://community.hwbot.org/topic/147255-guide-skylake-memory-timings-on-asus-motherboards/

**Comment by integralfx** [comment]
> there is no MFR and some others in the guide.
> Unfortunately, for happy circumstances, I became the owner of such a wonderful memory.

My DDR4 OC guide isn't made for a specific IC. It's a generic guide that can be applied for any IC. Just because MFR isn't listed in the tRFC suggestions, doesn't mean you can't overclock it. Try and see what works for you.

**Comment by shikulja** [comment]
I understand that this instruction is universal, and only helps in overclocking the memory, but the relevance of this instruction drops dramatically when you have to look for information elsewhere.

Also on my mfr, the readings tWTRS tWTRL - tWRRD_dg/sg are very different from the data from the table
![Скриншот 19-12-2019 182813](https://user-images.githubusercontent.com/3386359/71186410-3817b680-228e-11ea-8959-e8468a4394c9.png)

what is even more interesting if you set tWRRD_dg to 16 which memory can work, then tWTRS takes a value from many digits, something like 247875 I don’t remember exactly.
Perhaps the forums know this, but for me it turned out to be strange, and so far there is no such information in the instructions.

**Comment by integralfx** [comment]
> Also on my mfr, the readings tWTRS tWTRL - tWRRD_dg/sg are very different from the data from the table
> ![Скриншот 19-12-2019 182813](https://user-images.githubusercontent.com/3386359/71186410-3817b680-228e-11ea-8959-e8468a4394c9.png)

> **Disclaimer**: The silicon lottery will affect your overclocking potential so **there may be some deviation from my suggestions.**
> Here are my **suggestions** for the rest of the secondaries:

I only suggest timings to try. If you can do tighter timings then good for you.

> what is even more interesting if you set tWRRD_dg to 16 which memory can work, then tWTRS takes a value from many digits, something like

From your first screenshot, you can see that `tWRRD_dg - 19 = tWTR_S`. `18 - 19 = -1`, but I assume the values are stored as unsigned 32 bit integers, it'll actually be the maximum value (4294967295). Not sure what happens internally tho. I'd assume the value gets substituted for something that works, as you can't have negative timings.
