### ISSUE TITLE
EoL - but still works?

### ISSUE THREAD

**Issue by FlyingT** [integralfx/MemTestHelper#17]
Even though MemTestHelper crashes (or is crashed..) the basic fuction of opening the instances of MemTest with correct amount of RAM still works, right? We just lose the nice overview it gave us?

Also, just wondering .. shouldn't the last instance use "all unused ram" ?

**Comment by integralfx** [comment]
> the basic fuction of opening the instances of MemTest with correct amount of RAM still works, right? We just lose the nice overview it gave us?

Yep, MemTestHelper will still open the instances, just that after that HCI MemTest will close it.

> Also, just wondering .. shouldn't the last instance use "all unused ram" ?

No because each instance will have an equal amount of memory being tested.
