### ISSUE TITLE
Not working with 6.0.1 pro?

### ISSUE THREAD

**Issue by chrcoluk** [integralfx/MemTestHelper#18]
Hi

I see you at least used to support 6.0.1 in pre 6.4 builds, I tried them out, but when I hit the run button, it launches the HCI memtest processes, but then nothing happens, they are launched as if I launched manually, awaiting input of ram amount and to hit start.

Is this only for the non pro version?

**Comment by integralfx** [comment]
Yes, MemTestHelper only supports the free version.

It waits for the message boxes to pop up to close them, but the pro version doesn't have them so it just times out.
