### ISSUE TITLE
failed to start Memtest instance

### ISSUE THREAD

**Issue by Lay4U** [integralfx/MemTestHelper#21]
![image](https://user-images.githubusercontent.com/31833270/81600012-eff75d00-9403-11ea-810d-8a8a81b80049.png)

How can I Solve this?

I use MemTestHelper v2.2.0

and MemTest 6.2

http://www.mediafire.com/file/pd57k0dkj9p0722/MemTest62.zip/file

**Comment by integralfx** [comment]
You can try increasing the time out in settings.
