### ISSUE TITLE
Add setting tCWL as an step for finding a baseline

### ISSUE THREAD

**Issue by Leemonn** [integralfx/MemTestHelper#22]
Hello, I'm an Intel user and I've been running my b-die kit at 18-17-17-38 for a few days until I realized "what if I first set tCWL to an even number because maybe MAYBE my mobo was setting it to an odd number and that's what caused instability".
So now I am at c15 which is WAY better. I followed each step but I think this is very important to do to find a baseline.
Something like:
On Intel:
- Set tCWL = tCAS or +1 to make it even. Using odd tCWL may cause instability.

**Comment by KingFaris10** [comment]
I think what you're asking is already in the guide:
> Some motherboards don't play nice with odd tCWL. For example, I'm stable at 4000 15-19-19 tCWL 14, yet tCWL 15 doesn't even POST. Another user has had similar experiences.

**Comment by Leemonn** [comment]
Yep but that's after you change the primary timings. If you follow the steps you will read the tCWL thing too late. That's why I think it should be specified BEFORE changing primary timings.

**Comment by integralfx** [comment]
This has been addressed in https://github.com/integralfx/MemTestHelper/pull/23

**Comment by Leemonn** [comment]
Thank you! Also if you have time accept me on Discord (Lemon), I don't know if you are interested but I can make MemTestHelper work again with latest version of MemTest ;)

**Comment by integralfx** [comment]
> Thank you! Also if you have time accept me on Discord (Lemon), I don't know if you are interested but I can make MemTestHelper work again with latest version of MemTest ;)

Thanks but I don't want to play cat and mouse with the HCI devs.
