### ISSUE TITLE
memtesthelper closes itself as soon as I started the test 

### ISSUE THREAD

**Issue by 123khaled123** [integralfx/MemTestHelper#25]
As soon as I started the test the program crash but the test work just fine. tried to change "start minimize" but it doesnt work.

**Comment by integralfx** [comment]
As of HCI Memtest v6.4, MemTestHelper will be closed after clicking run.

https://github.com/integralfx/MemTestHelper/issues/8

HCI released their own launcher that basically does what MemTestHelper does.
