### ISSUE TITLE
Link to Malware in readme

### ISSUE THREAD

**Issue by XenHat** [integralfx/MemTestHelper#27]
The software named "Thaiphoon Burner" linked in **DDR4 OC Guide.md** resides on a website flagged as "contains trojan" by Malwarebytes, and does seem to [actually contain malware](https://www.virustotal.com/gui/file/f1aa1b86d4081abab3bb22fc2e8ff2903893f7a14e14e2b10bc4332623d83d8d/detection).

Trojan also found in **TM5** and **y-cruncher**

If this isn't some kind of IQ test, I would very strongly suggest not recommending users to install this.

**Comment by integralfx** [comment]
Thaiphoon reads the SPD chip on your RAM so it needs hardware level access, which other malware are known to need.

TM5 and y-cruncher has been around for a long time and has been used by many overclockers so I highly doubt they're malware.

There are many other ways to figure out the IC of your RAM. You don't even need to know the IC to overclock it.

There are also many other memory tests you can use.

Obviously, if you don't trust it, don't use it but many of us have been using them without any consequences.

**Comment by XenHat** [comment]
What's confusing is that other low-level software don't trigger these warnings. Chain of trust issue? Classic "Not whitelisted" behaviour?

As a side note, I've ran Thaiphoon and it seems ok. If there truly is no malware in there, it just fueled my disdain for the whole "Antivirus" "conspiracy" even more. Why would "Hardware Probe" show up as Generic.Trojan? Super useless.

P.S. Thaiphoon was unable to truly ID my ICs, but, It's pretty much G.Skill's fault for not filling in the data. Looks intentionally blank. It's SK Hynix [B/C/D]JR, which I already knew.

**Comment by alanbork** [comment]
the core issue is that anti-virus vendors no longer hand-analyse anything
unless it's already infected millions of machines. so everything is
heuristics based, and anything that works close to the hardware is
suspicious.
