### ISSUE TITLE
very poor bandwith compared to expectations on 3900mhz

### ISSUE THREAD

**Issue by sokolinek** [integralfx/MemTestHelper#29]
I don't know where to go with the question (I have used some Fb groups and forums but noone is helpful so far). I got Viper Steel Patriot 4400mhz 19CL, unfortunately doesn't work stable on any xmp profile so I needed to find something on my own (I am now a novice in ram oc) and finally I have found two stable setups:
-3600mhz 15-15-15-35 at 1,4V (vccio&vccsa at 1,15V)
-3900mhz 15-15-15-35 at 1,49V (vccio&vccsa at 1,2V).
I have i9 10900k and gigabyte z490 aorus ultra.
Normally I would say that going from 4400mhz 19CL to 3900mhz 15CL is super good but my bandwith in aida benchmark is super super bad - only around 40 GB/s (latency around 43ns). If I jump to 4000 mhz (unfortunately cannot get stability, whatever I do) I have the expected 57 GB/s. So just 100 mhz difference is around 17 GB/s higher. What could cause it? So far it seems like my PC isn't happy with speed below 4000mhz and something is bottlenecking here... And 40GB/s bandwith I should have on something like maybe 2900 mhz, not 3900 mhz.
I would really appreciate your help, it gets me crazy...

**Comment by integralfx** [comment]
Answered on your [reddit thread](https://www.reddit.com/r/overclocking/comments/jyh6ez/very_poor_bandwith_on_3900mhz/)
