### ISSUE TITLE
Notes to include in your guide

### ISSUE THREAD

**Issue by nitorita** [integralfx/MemTestHelper#31]
I highly advise warning that corruption is possible during RAM overclocking, and to advise users to regularly do sfc /scannow checks every so often after a change is made to make sure there isn't any. From personal experience, tRFC+tRP and RTL/IOLs can potentially cause corruption if overly tightened.

Over extensive testing, I have found that tRCD+tRP raises the IMC voltage requirement. Thus, I suggest tweaking it after all other timings are done rather than in the beginning, as other timings tweaks may be stable but instability could be wrongly attributed due to insufficient IMC voltage. This is a good resource for common BSOD error codes: https://www.reddit.com/r/overclocking/comments/atwtt5/psa_bsod_codes_when_ocing_and_possible_actions/

When tRFC is too tight, the PC can freeze, so that is something to mention for people to keep in mind. Also, increasing VDIMM allows tRFC to be tightened further. Here is a convenient chart of tRFC values to test (not mine): https://i.imgur.com/6Zg1MKy.png

Due to RAM being heat sensitive, it is recommended (for gamers) to perform a lengthy game test at least 80% GPU usage to test whether the GPU's ambient heat will cause the PC to BSOD. I suggest a constant test of at least six hours; I've had BSODs occur anywhere between 1-5 hours.

The explanation for tRC is somewhat confusing; rewording it would be nice. An easy way to explain it would be: If reducing tRFC+tRP and tRAS can boot but cannot pass TM5, gradually raise tRAS.

The easy way to tighten RTL and IOLs is to first train them on Auto and then for every -1 decrease in IOL, you want to decrease the same matching RTL by -1. It is sometimes more efficient and stable for all IOLs to be same. Some motherboards do not like when IOLs are manually changed, so you would increase the IOL Offset instead.

At the end of the guide, you could add a note that those with Samsung B-die or Micron B/E-die _can_ experiment raising their voltage beyond the 1.5V JEDEC spec, at their own risk and discretion. Up to 1.6V should be safe for most people, so long as they have proper cooling for their RAM. This will allow a further reduction of CAS latency and increase of frequency.

You should advise people to run a benchmark such as AIDA64 after each change to make sure there is an actual improvement in performance. Many timings have regressive performance if they are set too low.

**Comment by integralfx** [comment]
> Also, increasing VDIMM allows tRFC to be tightened further.

Not on all ICs. 

> The explanation for tRC is somewhat confusing; rewording it would be nice.

Yeah I've had a few people tell me it was a bit confusing. I'll reword it.

> At the end of the guide, you could add a note that those with Samsung B-die or Micron B/E-die can experiment raising their voltage beyond the 1.5V JEDEC spec, at their own risk and discretion. Up to 1.6V should be safe for most people, so long as they have proper cooling for their RAM. This will allow a further reduction of CAS latency and increase of frequency.

There are sticks rated at 1.65v XMP on the [B550 Unify-X Renoir QVL](https://www.msi.com/Motherboard/support/MEG-B550-UNIFY-X#support-mem-20) which suggests that it's safe to daily that at least on Renoir. On Ryzen 3000/5000 there is a kit rated at 1.6v so it's potentially safe to daily 1.6v.

> You should advise people to run a benchmark such as AIDA64 after each change to make sure there is an actual improvement in performance. 

Already in the guide in the tightening timings section.

Thanks for your notes. I'll add them in the guide.

**Comment by nitorita** [comment]
I did a bit more testing regarding specific timings. I tried super tightening them just to see how things would turn out.
(Note: For the AIDA64 numbers I quote, I am using RAM at 4,200 MHz.)

tWR can go below 10 (the lowest I could boot with was 5), but the RWC speeds and latency basically did not change compared to 10. I suggest 10 as the lowest practical value.

tRRD_S/tFAW can go all the way down to 1/4 or 2/8, but Read speeds take about a -600 MB/s penalty at both settings, and Copy is slightly reduced as well. Latency increases by 0.1 ns (not an outlier; this is after 30+ tests).
But, if you set tRRD_S/tFAW to 3/12, Read speeds will increase by around +100 MB/s and latency will drop by 0.3 ns. I highly suggest 3/12 as the extreme target.

tWTR_S can go down to 1, but after 30+ tests, it is basically the same as 2 but with very volatile latency. 2 provides the best performance.
Also, tWTR_L can go down to 4 for better performance (that's the lowest I can post with, so I'm not sure about performance below it).

tRTP below 8 incurs a _steep_ latency penalty. 8 should be the lowest value to strive for.

tRDWR_## can cause freezing if it is too tight. tWRRD_dd can be dropped to the floor, but performance was worse and there were irregularities when using the PC. Try to stay around 4 for that particular tertiary.

tCKE can be set to 0, depending on the PC. But I've read reports from others that the results are mixed, so I highly suggest benching to make sure performance doesn't worsen the lower you go.

tRAS sometimes doesn't like even numbers and refuses to post at them. In that case, round up/down.

**Comment by integralfx** [comment]
> tRCD+tRP is both voltage and heat sensitive, which means that there is a sweet spot effect with VDIMM.

That's dependent on the IC.

> For good practice, RAM should be flushed whenever there is a BSOD or errors detected in TM5. Latent errors can get left behind in the RAM, causing subsequent tests to throw errors as well (and even with stable overclocks). To do so, shut down and disconnect the power for at least 30-60 seconds.

AFAIK errors are when you write a value and the value read back isn't the same. The values themselves aren't errors, but just numbers. Not sure what you mean by "errors can get left behind".

> I highly suggest recommending 1usmus' config for TM5 as as another option for the TM5 config. He is the creator of the famous Ryzen DRAM Calculator, and it is a very thorough test that is quicker than anta777's and also incredibly accurate.

I did try 1usmus' config but anta777's was faster at finding errors in my experience. It's a decent config nonetheless.

> Here is a link to a helpful resource for diagnosing TM5 errors.

Some of the descriptions are a bit vague and with the way the guide suggests to tighten timings, whatever timing was last changed will be the cause.

>  On a side note, I believe you should make a thorough section about RTLs and IOLs, simply because it drastically increases bandwidth and lowers latency. When they are properly set, it is almost equivalent to dropping tCL by 1-2. Unlike other timings, they are linked, so you must lower both the RTL and the equivalent IOL together, or else it won't post. Here is a guide that clearly summarizes how they work.

I agree but I don't have an Intel setup so that's out of of scope for now. The guide seems good but as it's machine translated I wouldn't vouch for the accuracy of the information.

**Comment by nitorita** [comment]
What I meant by "errors left behind" is that, if I get BSODs or errors in TM5, and then I restart the PC and revert bad timing value to even a stable one, it can throw an error in TM5 when it never threw one before. This is just a flaw with how RAM works; the RAM doesn't always flush clean. You have to completely disconnect the power so the RAM can clear out. This is important to mention, since people may consider quickly changing timings to other values to test, but can't figure out why memory tests keep failing when some values might actually be stable.

Most on Overclock.net follow the same method of tightening RTLs and IOLs, so they can vouch for its accuracy. If anything, the current (older) guide you linked is much more confusing to follow and shouldn't be referred to. Considering how significant of a performance boost there is with the RTLs and IOLs, I don't see why it should be omitted from the guide. Again, I've simplified it already, you can copy it verbatim if you wish:

Set all IOLs to the same value and gradually reduce them together by 1. Since the RTLs are linked to the IOLs, they must be reduced by 1 as well.

It's a lot simpler than it sounds, since motherboards only accept specific RTL/IOL values and absolutely refuse to POST otherwise. The RTL/IOLs cannot be reduced individually. On some motherboards, they do not like when the RTL/IOLs are manually reduced, so the alternative is to raise the IOL Offset instead, which gives a similar result but should only be used as a last resort as it doesn't always play nice with RAM.

**Comment by integralfx** [comment]
> tRRD_S/tFAW can go all the way down to 1/4 or 2/8, but Read speed take a steep penalty at those settings, and Copy speed is slightly reduced as well. Latency also slightly increases.
However, if you set tRRD_S/tFAW to 3/12, Read speeds will increase by a decent amount and latency will drop significantly, compared to 4/16. I suggest 3/12 as the Extreme target.

> tWTR_S can go down to 1, but it is basically the same as being set to 2 but with incredibly volatile latency. 2 provides the best performance overall.
tWTR_L can go down to 4 for better performance (that's the lowest I could test; it could go lower for others).

> tRTP below 8 incurs an insane latency penalty. 8 should be the absolute lowest value to strive for.

MLC:
![image](https://user-images.githubusercontent.com/16512539/107706398-59e6bf00-6d14-11eb-8c72-4006ad4eb380.png)

AIDA:
![image](https://user-images.githubusercontent.com/16512539/107706682-cbbf0880-6d14-11eb-9517-7985ccbf7781.png)

Doesn't seem to make much of a difference and in some cases performance was slightly worse.

Much thanks to Tyllo for testing this.
