### ISSUE TITLE
Some questions/requests

### ISSUE THREAD

**Issue by dardoor** [integralfx/MemTestHelper#33]
Since HCI Memtest is still one of the best RAM testing programs, I'd like to use your tool or something like it.

1. Why is there a 2GB limit in MTHelper (in the case I want fewer threads), even though I can run Memtest standalone with 3GB and it seems to work fine?
2. Is there a link to Memtest 6.4 before it was modified? Is it even needed? I have 5.0 and it seems to work just fine (DDR4 on Z490). It found errors even a bit faster than 6.3 and 7.0, but maybe that was just coincidence.
3. Is there a way to prevent opening of the browser/link when an error is found? If not that would be nice to have.

**Comment by integralfx** [comment]
1. I and many others have found that HCI MemTest only reliably allows 2048MB. More might work as you've found but to make it work for everyone I've limited it to 2048MB. In hindsight, the limit isn't needed but that's just how it is now.
2. [memtest.zip](https://github.com/integralfx/MemTestHelper/files/5737442/memtest.zip)
3. Not without modifying the MemTest executable.

**Comment by alanbork** [comment]
There seems to be a virus in the attached memtest.zip file.

**Comment by dardoor** [comment]
@integralfx: Thanks, works great! @alanbork: there must be an issue on your end.

One more question: is disabling the page file required, or recommended?
Supposedly for the Ryzen DRAM Calculator (which also includes HCI Memtest) it's not needed, but that utility also runs with admin rights, so maybe it has a way to check for the pagefile.

Speaking of the Ryzen DRAM Calculator: I just ran Memtest with it for over 2 hours with no errors, but running it with the MemTestHelper found an error in seconds. After disabling the page file and restarting, the DRAM Calculator also showed an error quickly. Weird. I think I'm going to trust the Helper more.

**Comment by integralfx** [comment]
> One more question: is disabling the page file required, or recommended?

It's a good idea to leave it enabled so that if you run out of RAM, unused processes will go to the page file.

> Speaking of the Ryzen DRAM Calculator: I just ran Memtest with it for over 2 hours with no errors, but running it with the MemTestHelper found an error in seconds. After disabling the page file and restarting, the DRAM Calculator also showed an error quickly. Weird. I think I'm going to trust the Helper more.

The DRAM Calculator uses an older version of HCI MemTest so that may be why. Either way, it's a good idea to use multiple programs to test.

**Comment by dardoor** [comment]
Ok, thanks. One more thing, though. I've ran the Helper for a few hours with the above HCI Memtest 6.4 and at some point the Helper window just vanished. It was there for around 2-3 hours, but sometime after that it disappeared. Is this normal?

**Comment by integralfx** [comment]
> Ok, thanks. One more thing, though. I've ran the Helper for a few hours with the above HCI Memtest 6.4 and at some point the Helper window just vanished. It was there for around 2-3 hours, but sometime after that it disappeared. Is this normal?
> EDIT: it happened again now, but after only 20-30 minutes. The Memtest instances just kept on going, though.

That shouldn't happen. Does it happen with older versions of HCI MemTest?

**Comment by dardoor** [comment]
I don't think I've noticed it with 5.0 yet, I'm not 100% sure though.
With 7.0 the window goes away after a few seconds, but I assume you're aware of this and it happens to everyone.

**Comment by KlosiakMK** [comment]
@integralfx Very nice and useful tool. Many thanks for developing. 

1. I can confirm that when using MemTestHelper v2.2.0 with the latest HCI memtest 7.0 main windows disappears just after HCI instances start to work. This causes that I am not able to set when to stop test (coverage level) and probably stop on error won't work too unfortunately.

2. I have 16C/32T CPU and I have noticed that tool is not capable to handle more than 16 threads setting. Up to 16 threads it works fine (besides issue described above) but over 16 threads tool is not able to launch all HCI memtest instances and order windows in a nice one in rows.

**Comment by integralfx** [comment]
@KlosiakMK 

1. https://github.com/integralfx/MemTestHelper/issues/8
2. MemTestHelper is deprecated. If you want to use the latest version of HCI MemTest, buy the pro version and use the developer's launcher.

**Comment by KlosiakMK** [comment]
@integralfx Thx...now I know what is the root cause and understand why your utility is EOL.

BTW...do you have any idea where to find old versions of HCI MemTest? I mean v5.0 and v6.4. I am outside US and they want to pay in the physical cash...and don't want to use PayPal. What a rubbish. I would pay for the pro version but they are not making things easy.

**Comment by Snoop05** [comment]
@KlosiakMK Wayback Machine should be able to help with that.
(e.g. 6.1 http://web.archive.org/web/20190521101553/https://www.hcidesign.com/memtest/MemTest.zip)

Also integralfx already linked in second post of this thread.

**Comment by KlosiakMK** [comment]
> @KlosiakMK Wayback Machine should be able to help with that. (e.g. 6.1 http://web.archive.org/web/20190521101553/https://www.hcidesign.com/memtest/MemTest.zip)
> 
> Also integralfx already linked in second post of this thread.

Thanks! This link above links to version 6.1. I have found a version 6.4 which works with MemTestHelper v.2.2.0 :)
