### ISSUE TITLE
tWTRS/L relation to tWRRD_dg/sg

### ISSUE THREAD

**Issue by ArmaWizard** [integralfx/MemTestHelper#37]
I quote:

`On Intel, tWTRS/L should be left on auto and controlled with tWRRD_dg/sg respectively. Dropping tWRRD_dg by 1 will drop tWTRS by 1. Likewise with tWRRD_sg. Once they're as low as you can go, manually set tWTRS/L.`

Ok understood; but what does this mean: "Once they're as low as you can go, manually set tWTRS/L.`"
Because you give suggested timings for tWTRS/L; does this mean I should drop tWRRD_dg/sg until tWTRS/L reaches the suggested timings per your sheet? And then set them again manually, to be sure? Because if I drop my  tWRRD_dg/sg by 1 on my kit, I've already reached tWTRS/L as per suggested "Tight" timings.

Or do I manually set the tWTRS/L timings and then try to "go as low as I can" with tWRRD_dg/sg?

Greetings,
Merlin

**Comment by integralfx** [comment]
> does this mean I should drop tWRRD_dg/sg until tWTRS/L reaches the suggested timings per your sheet?

> And then set them again manually, to be sure?

Yep

**Comment by ArmaWizard** [comment]
Thank you very much!
