### ISSUE TITLE
Always get this error: Amount of RAM must be an integer

### ISSUE THREAD

**Issue by recklessnl** [integralfx/MemTestHelper#4]
I keep getting this error no matter what value I do as input. 1, 3, 8, 200, 16000, 16384, 2048, 4096 - I've tried all these values and every single one gives me this error.

Any ideas? This tool is completely unusable at the moment.

**Comment by integralfx** [comment]
Hmm that's strange.

Can you download 
[this version of MemTestHelper](https://github.com/integralfx/MemTestHelper/files/3797256/MemTestHelper2.zip) and upload memtesthelper.log?

**Comment by integralfx** [comment]
Try v2.1.0 but if that doesn't work, upload memtesthelper.log

**Comment by Chicos123** [comment]
w10 x64 1909 18363.449 
hci 6.4
helper 2.1.0

![error](https://user-images.githubusercontent.com/23288869/68081763-682e0600-fe56-11e9-9df7-120f039f5d0f.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3801315/memtesthelper.log)

**Comment by Chicos123** [comment]
w10 x64 1909 18363.449 
hci 6.4
helper 2.1.0

![error](https://user-images.githubusercontent.com/23288869/68081811-1043cf00-fe57-11e9-8c3d-4f005ffdd0c8.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3801322/memtesthelper.log)
