### ISSUE TITLE
tRP and tRCD no longer linked on some Z690 boards

### ISSUE THREAD

**Issue by iiTsMus** [integralfx/MemTestHelper#56]
I can confirm that on MSI's Tomahawk and ASUS' TUF Z690 DDR4 boards tRP and tRCD are not linked. You can set different values for them and they will not default to using the highest number. They are utilising the separate RP and RCD registers of Alder Lake

I can also confirm Gigabyte has NOT followed suit, yet, unfortunately

Is there any information about what VDDq voltage we should be using for Alder Lake? I see VCCIO in the guide but that's not an option for 12th Gen

**Comment by integralfx** [comment]
Good to know

> Is there any information about what VDDq voltage we should be using for Alder Lake?

As far as I know it should be pretty similar to 10th Gen (1.35V max)

I think buildzoid mentioned it in some of his videos

**Comment by integralfx** [comment]
Added in https://github.com/integralfx/MemTestHelper/commit/bc19ca9121450f317a91b31908d5880c3f4deeb2
