### ISSUE TITLE
VCCSA/VCCIO voltages table header is shifted

### ISSUE THREAD

**Issue by KlosiakMK** [integralfx/MemTestHelper#59]
I think that in the IMC section table header for second column should be "VCCIO/VCCSA (V)" instead of "VCCSA/VCCIO (V)".

**Comment by integralfx** [comment]
![image](https://user-images.githubusercontent.com/16512539/199853143-609878ef-cffa-438e-b398-ef894ba83080.png)

If you're referring to this table, this is correct

The ranges apply to both VCCSA and VCCIO

What would swapping it achieve?

**Comment by KlosiakMK** [comment]
Yes, the ranges are fine but when I was reading the table I was mislead by the header and thought that for example in the first row we have pair VCCSA - VCCIO (1.15 - 1.20) and started to wonder why it is not corresponding with the rule that VCCSA should be 50mV higher than VCCIO. This is why I suggested to change VCCSA/VCCIO to VCCIO/VCCSA but now I think that I have head a bad day that time. Sorry for troubling you.

**Comment by integralfx** [comment]
> the rule that VCCSA should be 50mV higher than VCCIO.

That's not a rule, just a guideline
