### ISSUE TITLE
Not working with HCI MemTest 6.4

### ISSUE THREAD

**Issue by integralfx** [integralfx/MemTestHelper#6]
w10 x64 1909 18363.449 
hci 6.4
helper 2.1.0

![error](https://user-images.githubusercontent.com/23288869/68081811-1043cf00-fe57-11e9-8c3d-4f005ffdd0c8.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3801322/memtesthelper.log)

_Originally posted by @Chicos123 in https://github.com/integralfx/MemTestHelper/issues/4#issuecomment-549112141_

**Comment by integralfx** [comment]
@Chicos123
Try out [this version.](https://github.com/integralfx/MemTestHelper/files/3802935/MemTestHelper2.zip)

**Comment by Chicos123** [comment]
Fixed !!!
Thank you so much ! 
I'll use it well :D
![1](https://user-images.githubusercontent.com/23288869/68115322-815cb280-ff3b-11e9-8fa5-dc11c9ebccc9.png)

**Comment by Chicos123** [comment]
helper 2.1.1
log and screenshot

on my pc over 13000MB Show me error

![111](https://user-images.githubusercontent.com/23288869/68119067-05676800-ff45-11e9-9165-f63d65c01c58.png)
![222](https://user-images.githubusercontent.com/23288869/68119068-05676800-ff45-11e9-97f8-9a79e5003398.png)
![333](https://user-images.githubusercontent.com/23288869/68119069-05676800-ff45-11e9-82db-7896db009211.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3803831/memtesthelper.log)

**Comment by Chicos123** [comment]
helper 2.1.1
got error with over 13000MB

![111](https://user-images.githubusercontent.com/23288869/68119277-a35b3280-ff45-11e9-9e2c-1be890f4ea58.png)
![222](https://user-images.githubusercontent.com/23288869/68119278-a35b3280-ff45-11e9-81fb-204c4d5e84e9.png)
![333](https://user-images.githubusercontent.com/23288869/68119280-a35b3280-ff45-11e9-9a24-796c651a2a4c.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3803858/memtesthelper.log)

**Comment by Deathtech-00** [comment]
Can confirm still not working.

**Comment by integralfx** [comment]
@Chicos123 
1. I now get the MemTest dimensions when starting MemTestHelper, which is why you might see MemTest starting then exiting.
2. Not sure what causes that, but try the version linked. Make sure 'Verbose logging' is checked in settings.
3. I think I fixed that now.

[MemTestHelper2.zip](https://github.com/integralfx/MemTestHelper/files/3806992/MemTestHelper2.zip)

**Comment by Chicos123** [comment]
helper
helper 2.1.1 v1 and v2
got error randomly

v2 fixed window size 
i think it caused from different locale
![1a](https://user-images.githubusercontent.com/23288869/68198691-e37eeb80-ffff-11e9-9b50-88d6dd2081b7.png)
![1d](https://user-images.githubusercontent.com/23288869/68198695-e4b01880-ffff-11e9-8cbb-19dc6c170d58.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3808385/memtesthelper.log)

**Comment by Chicos123** [comment]
helper 2.1.1 v1 and v2
got error randomly

v2 fixed window size
i think it caused from different locale

![1](https://user-images.githubusercontent.com/23288869/68199495-7e2bfa00-0001-11ea-89c5-60254b61e3e8.png)
![22](https://user-images.githubusercontent.com/23288869/68199496-7e2bfa00-0001-11ea-9656-a335e320ac2d.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3808427/memtesthelper.log)

**Comment by integralfx** [comment]
@Chicos123 
I can see that you've tried different RAM sizes. The first time you tried 7750, it didn't work. You tried it again and it worked fine. :/

I'm still not sure why it's not finding the message boxes. 
[This version](https://github.com/integralfx/MemTestHelper/files/3811857/MemTestHelper2.zip) fixes a few issues and increases the timeout to 10 seconds, which means it'll try to find the message boxes for 10 seconds before giving up.

**Comment by Chicos123** [comment]
helper 2.1.1 v3

Still got error, but very few
seems to effective, increasing time out to 10 sec

![1](https://user-images.githubusercontent.com/23288869/68385323-dcd9ab00-019c-11ea-9769-d060e10c1b9e.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3819333/memtesthelper.log)

**Comment by Chicos123** [comment]
helper 2.1.1 v3

Still got error, but very few
seems to effective, increasing time out to 10 sec

![1](https://user-images.githubusercontent.com/23288869/68385806-eca5bf00-019d-11ea-91aa-d566f3d603b9.png)
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3819366/memtesthelper.log)

**Comment by integralfx** [comment]
Fixes / workarounds are added to [v2.2.0](https://github.com/integralfx/MemTestHelper/releases/tag/v2.2.0)
