### ISSUE TITLE
Gigabyte Z690 now allows different values for tRP and tRCD

### ISSUE THREAD

**Issue by iiTsMus** [integralfx/MemTestHelper#61]
Hello, a few months ago I said that Gigabyte didn't allow different values for tRCD and tRP on their 600 series intel boards. It was added into line 352 in this guide. `On Alder Lake CPUs, tRD and tRP are no longer linked as long as you are not using a Gigabyte motherboard`.

I can confirm that, after some messaging back and forward with their support team, they added the capability into the new BIOS version. I have used the F22 BIOS and it does let me use different values and it will train with them.

**Comment by integralfx** [comment]
Good to know

Does it show in software when you boot to Windows? (CPU-Z memory tab, Asrock Timing Configurator, etc.)

**Comment by cyring** [comment]
This is indeed specified in 12th gen datasheet

![2023-02-02-104817_585x625_scrot](https://user-images.githubusercontent.com/11563789/216293933-653b69d5-f2e0-40a2-9244-2c38610b4760.png)

**Comment by iiTsMus** [comment]
> Good to know
> 
> Does it show in software when you boot to Windows? (CPU-Z memory tab, Asrock Timing Configurator, etc.)

Yup. Both CPU and Atc show the different values
