### ISSUE TITLE
Asrock Timing Configurator Links Dead

### ISSUE THREAD

**Issue by integralfx** [integralfx/MemTestHelper#62]
> asrtc 4.0.10 dead, i suggest replacing with https://web.archive.org/web/20211010085116/http://picx.xfastest.com/nickshih/asrock/AsrTCSetup(v4.0.10).rar
astrc 4.0.13 also dead, not sure if this https://filehorst.de/download.php?file=ecporlpy as found here https://www.overclock.net/threads/official-intel-z690-z790-ddr4-daily-memory-overclock.1794799/ is legit

**Comment by BoringBoredom** [comment]
https://picx.xfastest.com/nickshih/asrock/AsrTCSetup(v4.0.14).rar

You can replace the version number in the URL to grab older/newer versions.

**Comment by integralfx** [comment]
https://github.com/integralfx/MemTestHelper/commit/4fe7082eb03c550e151d109d4f62552418c9bd92
