### ISSUE TITLE
Dead links across document

### ISSUE THREAD

**Issue by previousserver** [integralfx/MemTestHelper#64]
Server mod here and I'd like to chime in on a few dead links apart from the ones in #62.

> Note: Thaiphoon is known to guess ICs, so it shouldn't be fully trusted. It's highly recommended to check the label on the sticks if possible.
> See [here](https://www.reddit.com/r/overclocking/comments/ig9d76/thaiphoon_burner_cluelessly_guessing_memory_ics/) for more info.

dead, looked around no backups

> G.Skill 042 Code
> Similar to Corsair, G.Skill uses a 042 code to indicate the ICs.
> Example: 04213X8810B
> The first bolded character is the density. 4 for 4 Gb, 8 for 8 Gb, and S for 16 Gb.
> The second bolded number is the manufacturer. 1 for Samsung, 2 for Hynix, 3 for Micron, 4 for PSC (powerchip), 5 for Nanya, and 9 for JHICC.
> The last character is the revision.
> This is the code for Samsung 8 Gb B-die.
> See the [r/overclocking wiki](https://www.reddit.com/r/overclocking/wiki/ram/ddr4#wiki_new_markings_-_.22042_code.22_table) for a full list.

wrong navigation (I was the one who made the breaking change a couple years ago 😅 and deleted my Reddit acc since), should be [this](https://www.reddit.com/r/overclocking/wiki/ram/ddr4/#wiki_042.2Ft42.2F043.2Fetc._code_current_theory)

> For Asus Maximus boards:
> Play around with the Maximus Tweak Modes; sometimes, one will post where the other does not.
> You can enable Round Trip Latency under Memory Training Algorithms to let the board attempt to train RTL and IOL values.
> If you can't boot, you can try tweaking the skew control values.
> More info [here](https://rog.asus.com/forum/showthread.php?47670-Maximus-7-Gene-The-road-to-overclocking-memory-without-increasing-voltage).

forums broken, no content loaded, archive.org copies are barely better (text only)

> On Ryzen 3000 and 5000, [1usmus](https://www.overclock.net/forum/13-amd-general/1640919-new-dram-calculator-ryzena-1-5-1-overclocking-dram-am4-membench-0-7-dram-bench-480.html#post28049664) suggests 28Ω - 40Ω. Lower settings may be harder to run but potentially helps with voltage requirements.

dead

> This value is not to exceed 1.10V on Ryzen 3000 and 5000, and should always be restricted to at least 0.10V less than DRAM Voltage.
> Source: [AMD](https://community.amd.com/t5/blogs/community-update-4-let-s-talk-dram/ba-p/415902)

dead, archive avail

[Impact of RAM on Intel's Skylake desktop architecture by KingFaris](https://kingfaris.co.uk/intel-ram-oc-impact) moved, should be [this](https://kingfaris.co.uk/blog/intel-ram-oc-impact/)
[Intel Memory Overclocking Quick Reference by sdch](https://www.overclock.net/forum/27784556-post7836.html) dead, archive avail
[The road to overclocking memory without increasing voltage by Raja@ASUS](https://rog.asus.com/forum/showthread.php?47670-Maximus-7-Gene-The-road-to-overclocking-memory-without-increasing-voltage) broken, see above

**Comment by integralfx** [comment]
https://github.com/integralfx/MemTestHelper/commit/57a8c9a29c29b46208e2e9cfb40962cff7be692b

**Comment by ValeZAA** [comment]
Link for Msi Dragon Ball is dead. https://forum-en.msi.com/index.php?threads/msi-forum-moderator-tool-space-%E2%80%93-bios-software-dragon-ball-power.380646/
