### ISSUE TITLE
DDR5 Update

### ISSUE THREAD

**Issue by johnnyde94** [integralfx/MemTestHelper#66]
Is it possible to have a similar document with DDR5 info, I think the stuff here is amazing it would be great to have a version for ddr5.

**Comment by integralfx** [comment]
Maybe when the DDR5 platform becomes more affordable but there are lots of resources floating around like buildzoid's videos, overclock.net forums, etc

Currently there is no plan in the near future though others may want to volunteer and write a guide themselves

**Comment by aliajboy** [comment]
I hope you write for DDR5 like this one. I'm waiting for your update. thanks

**Comment by ValeZAA** [comment]
Now there is no more DDR4 on Arrow Lake, lol
