### ISSUE TITLE
Can't open DDR4 OC Rankings

### ISSUE THREAD

**Issue by ghost** [integralfx/MemTestHelper#68]
Have Access Denied error when I am trying to open [DDR4 OC Rankings](https://docs.google.com/spreadsheets/d/1NN3-m-mvqxoebSUO_22efkMrnGog2y1atWUgiZSZTOc/edit?usp=sharing) from [here](https://github.com/integralfx/MemTestHelper/blob/oc-guide/DDR4%20OC%20Guide.md#information). Tried to open this with two accounts. Don't know if it should be so.

**Comment by integralfx** [comment]
I have the same issue

I'm not sure who owns that spreadsheet but I've removed it now
