### ISSUE TITLE
Helper v2.2.0 crash

### ISSUE THREAD

**Issue by Chicos123** [integralfx/MemTestHelper#8]
if you're testing very close to free ram size
helper getting crash .. 😢 
![1](https://user-images.githubusercontent.com/23288869/68521576-d73bac80-02e5-11ea-9e46-dcdbe361acd5.gif)

**Comment by integralfx** [comment]
Can you check 'Verbose logging' and post memtesthelper.log?

**Comment by Dodgexander** [comment]
> Can you check 'Verbose logging' and post memtesthelper.log?

Here's the log, (I have the same problem).
[memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3855355/memtesthelper.log)

**Comment by integralfx** [comment]
> > Can you check 'Verbose logging' and post memtesthelper.log?
> 
> Here's the log, (I have the same problem).
> [memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3855355/memtesthelper.log)

Hmm...
I don't see anything wrong in the log file.

Can you go into Event Viewer > Windows Logs > Application and find the MemTestHelper crash? Right click the event and go copy > copy details as text and post it here?

**Comment by Dodgexander** [comment]
> > > Can you check 'Verbose logging' and post memtesthelper.log?
> > 
> > 
> > Here's the log, (I have the same problem).
> > [memtesthelper.log](https://github.com/integralfx/MemTestHelper/files/3855355/memtesthelper.log)
> 
> Hmm...
> I don't see anything wrong in the log file.
> 
> Can you go into Event Viewer > Windows Logs > Application and find the MemTestHelper crash (filter current log should help with this)? Right click the event and go copy > copy details as text and post it here?

There's no detail in Event Viewer at all.

The application just disappears with no trace like in the opening post of this issue

**Comment by integralfx** [comment]
> There's no detail in Event Viewer at all.
> 
> The application just disappears with no trace like in the opening post of this issue

I figured out what's causing MemTestHelper to "crash".

!["Crash"](https://i.imgur.com/oCOJNq3.png)

As you can see, HCI MemTest is finding MemTestHelper and closing it.

I have HCI MemTest v6.4 but that was before I released MemTestHelper v2.2.0. I downloaded v6.4 again and MemTestHelper closes after 5-10 seconds.

![Comparison](https://i.imgur.com/MUo380k.png)

Top is before MTH v2.2.0 was released. Bottom is after.

It's not too hard to fix it but clearly the HCI devs don't like me, even tho the DRAM Calculator includes the same functionality to automate HCI MemTest.

Consider MemTestHelper EOL.

The DDR4 OC Guide will still be updated tho.

**Comment by Dodgexander** [comment]
> > There's no detail in Event Viewer at all.
> > The application just disappears with no trace like in the opening post of this issue
> 
> I figured out what's causing MemTestHelper to "crash".
> 
> !["Crash"](https://camo.githubusercontent.com/3a61688ea86cd57fa957e60d8f7757416ca270d3/68747470733a2f2f692e696d6775722e636f6d2f4f695a42515a6c2e706e67)
> 
> As you can see, HCI MemTest is finding MemTestHelper and closing it.
> 
> I have HCI MemTest v6.4 but that was before I released MemTestHelper v2.2.0. I downloaded v6.4 again and MemTestHelper closes after 5-10 seconds.
> 
> ![Comparison](https://camo.githubusercontent.com/13fcf3ae6d3e34ca95653a321f375342d338135d/68747470733a2f2f692e696d6775722e636f6d2f4d556f3338306b2e706e67)
> 
> Top is before MTH v2.2.0 was released. Bottom is after.
> 
> It's not too hard to fix it but clearly the HCI devs don't like me, even tho the DRAM Calculator includes the same functionality to automate HCI MemTest.
> 
> Consider MemTestHelper EOL.
> 
> The DDR4 OC Guide will still be updated tho.

Well that makes sense, I guess...

Another free OC tool following the paid path. Already saw Passmark Memtest86 demand pro for more than 4 passes!

Thanks for your work putting this together, I guess I will try and get hold of an older version.

**Comment by alanbork** [comment]
Well now what did you expect for a tool that encourages people to not buy
the paid version of MemTest? That even hides the fact that you are using
the free version?

FYI you can avoid the blacklist if you change your tool to use the pro
version only.

**Comment by 13Dima13** [comment]
> HCI MemTest is finding MemTestHelper and closing it.
Maybe creating a random process name of MemTestHelper and random window name would solve this issue.

**Comment by integralfx** [comment]
> > HCI MemTest is finding MemTestHelper and closing it.
> 
> Maybe creating a random process name of MemTestHelper and random window name would solve this issue. Easy to implement I suppose and show f*ck to HCI.
> 
> Their implementation is awful, some student level and they can`t find process which run them - only by name, easy to get around.

There are ways around it as you've mentioned above, but I don't want to invest time fighting the developers. If you want to use the latest version, you can buy HCI pro.

**Comment by 13Dima13** [comment]
> 
> 
> > > HCI MemTest is finding MemTestHelper and closing it.
> > 
> > 
> > Maybe creating a random process name of MemTestHelper and random window name would solve this issue. Easy to implement I suppose and show f*ck to HCI.
> > Their implementation is awful, some student level and they can`t find process which run them - only by name, easy to get around.
> 
> There are ways around it as you've mentioned above, but I don't want to invest time fighting the developers. If you want to use the latest version, you can buy HCI pro.

You know it`s matter of principle, when they started play in such dirty game I will not buy PRO version. Very sad, that you are not support anymore your child.
Thanks for your work, I am appreciate that.

**Comment by alanbork** [comment]
If it's a matter of principle consider that you can use MemTestHelper with the pro version of HCI MemTest 7.0. The principle is paying for what you use rather than trying to find away around the nag screens in the free version by using a 3rd party app like MemTestHelper. If MemTestHelper had not obscured all evidence that it was using a shareware version of the app, it would not have been blocked.
